config/routes.rb
Timecast::Application.routes.draw do

  resources :users do
    member do
      put :suspend
      put :unsuspend
      delete :purge
    end
  end

  resource :session, :only => [:new, :create, :destroy]

  match 'signup' => 'users#new', :as => :signup
  match 'register' => 'users#create', :as => :register
  match 'login' => 'sessions#new', :as => :login
  match 'logout' => 'sessions#destroy', :as => :logout

  match '/activate/:activation_code' => 'users#activate', :as => :activate, :activation_code => nil

  resources :challenges

  root :to => "challenges#index"

end

app/models/challenge.rb
class Challenge < ActiveRecord::Base
  belongs_to :user

  named_scope :unassigned, :conditions => {:user_id => nil}

  ############
  # validations
  validates_presence_of :name
  validates_presence_of :estimate

  validates_numericality_of :estimate, :greater_than_or_equal_to => 0, :allow_nil => true, :only_integer => true
  validates_numericality_of :completedin, :greater_than_or_equal_to => 0, :allow_nil => true, :only_integer => true

  validate :start_before_stop


  ############
  # validation helpers
  
  def start_before_stop
    return if started_at.blank? || stopped_at.blank?
    errors.add :stopped_at, "must be after started-at!" if started_at >= stopped_at
  end


  ############
  # date helpers
  def started?
    self.started_at.present?
  end
  def stopped?
    self.stopped_at.present?
  end
  def aborted?
    self.aborted_at.present?
  end

  def done?
    started? && (stopped? || aborted?)
  end


  #######
  # Scoring-related helpers
  def estimated_stop_date
    (started_at || Time.now) + (estimate || 0).seconds
  end

  
  def status
    return "Aborted" if aborted?
    return "Completed" if done?
    return "Started" if started?
    "New"
  end
end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
  before_filter :find_challenge, :except => [:index, :new, :create]

  # GET /challenges
  # GET /challenges.xml
  def index
    if logged_in?
      @challenges = current_user.challenges.all
    else
      @challenges = Challenge.unassigned.all
    end

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @challenges }
    end
  end

  # GET /challenges/new
  # GET /challenges/new.xml
  def new
    if logged_in?
      @challenge = current_user.challenges.new
    else
      @challenge = Challenge.unassigned.new
    end

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @challenge }
    end
  end

  # POST /challenges
  # POST /challenges.xml
  def create
    if logged_in?
      @challenge = current_user.challenges.new(params[:challenge])
    else
      @challenge = Challenge.unassigned.new(params[:challenge])
    end

    respond_to do |format|
      if @challenge.save
        format.html { redirect_to(@challenge, :notice => 'Challenge was successfully created.') }
        format.xml  { render :xml => @challenge, :status => :created, :location => @challenge }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @challenge.errors, :status => :unprocessable_entity }
      end
    end
  end

  # GET /challenges/1/edit
  def edit
  end

  # GET /challenges/1
  # GET /challenges/1.xml
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @challenge }
    end
  end

  # PUT /challenges/1
  # PUT /challenges/1.xml
  def update
    # clean up date values that are to be set to 'now'
    [:aborted_at,:started_at, :stopped_at].each do |datefield|
       params[:challenge][datefield] = Time.now if params[:challenge][datefield].present? && params[:challenge][datefield] == 'now'
    end
    respond_to do |format|
      if @challenge.update_attributes(params[:challenge])
        format.html { redirect_to(@challenge, :notice => 'Challenge was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @challenge.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /challenges/1
  # DELETE /challenges/1.xml
  def destroy
    @challenge.destroy

    respond_to do |format|
      format.html { redirect_to(challenges_url) }
      format.xml  { head :ok }
    end
  end
  

  private

  def find_challenge
    begin
      if logged_in?
        @challenge = current_user.challenges.find_by_id(params[:id])
      else
        @challenge = Challenge.unassigned.find(params[:id])
      end
    rescue ActiveRecord::RecordNotFound
      flash[:error] = "Can't find that challenge!"
      return redirect_to challenges_path
    end
  end
end

app/helpers/challenges_helper.rb
module ChallengesHelper
end

app/views/challenges/_form.html.erb
<%= form_for(@challenge) do |f| %>
  <% if @challenge.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@challenge.errors.count, "error") %> prohibited this challenge from being saved:</h2>

      <ul>
      <% @challenge.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, :rows => 4 %>
  </div>
  
<% if @challenge.estimate.blank? %>  
  <div class="field">
    <%= f.label :estimate %><br />
    <%= f.text_field :estimate %>
  </div>
  <div>Minutes:</div>
  <div id="minSlider"></div>
  <div>Hours:</div>
  <div id="hourSlider"></div>
  <div> Days:</div>
  <div id="daySlider"></div>
<% else %>
  <div class="field">
    <%= f.label :estimate %><br />
    <%= @challenge.estimate %>
  </div>
<% end %>

<% if !@challenge.started? %>
  <div class="field">
    <%= f.label :started_at %><br />
    <%= f.datetime_select :started_at %>
  </div>
<% else %>
  <div class="field">
    <%= f.label :stopped_at %><br />
    <%= f.datetime_select :stopped_at %>
  </div>
  <div class="field">
    <%= f.label :completedin %><br />
    <%= f.text_field :completedin %>
  </div>
<% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= render :partial => 'stop_abort_buttons' if @challenge.started? && !@challenge.done? %>

app/views/challenges/_stop_abort_buttons.html.erb
    <%= form_for(@challenge) do |f| %>
            <%= f.hidden_field(:stopped_at, :value => 'now') %>
        <%= f.submit 'Stop now!' %>
    <% end %>

    <%= form_for(@challenge) do |f| %>
            <%= f.hidden_field(:aborted_at, :value => 'now') %>
        <%= f.submit 'Abort now!' %>
    <% end %>

app/views/challenges/edit.html.erb
<h1>Editing challenge</h1>

<%= render 'form' %>

<%= link_to 'Show', @challenge %> |
<%= link_to 'Back', challenges_path %>

app/views/challenges/index.html.erb
<%= image_tag "title.png" %>

<h1>Listing challenges</h1>

<% if @challenges.present? %>
	<table>
	  <tr>
		<th>Name</th>
		<th>Estimate</th>
		<th>Status</th>
		<th colspan="3">Actions</th>
	  </tr>

	<% @challenges.each do |challenge| %>
	  <tr>
		<td><%= challenge.name %></td>
		<td><%= challenge.estimate %></td>
		<td><%= challenge.status %></td>
		<td><%= link_to 'Show', challenge %></td>
		<td><%= link_to 'Edit', edit_challenge_path(challenge) %></td>
		<td><%= link_to 'Destroy', challenge, :confirm => 'Are you sure?', :method => :delete %></td>
	  </tr>
	<% end %>
	</table>
<% end %>

<br />

<%= link_to 'New Challenge', new_challenge_path %>

app/views/challenges/new.html.erb
<h1>New challenge</h1>

<%= render 'form' %>

<%= link_to 'Back', challenges_path %>

app/views/challenges/show.html.erb
<p id="notice"><%= notice %></p>

<% if !@challenge.done? %>

  <div>BIG clock goes here!!!</div>
  <div>ETA: <%= @challenge.estimated_stop_date %> </div>
  <%= render :partial => 'stop_abort_buttons' %>
<% else %>
  <div>Estimated stopping time was: <%= @challenge.estimated_stop_date %> </div>
  <% unless @challenge.aborted? %>
  <div>Your estimate was:
    <% if @challenge.estimated_stop_date > @challenge.stopped_at %>
      Short by <%= @challenge.estimated_stop_date - @challenge.stopped_at %>
    <% else %>
      Over by <%= @challenge.stopped_at - @challenge.estimated_stop_date %>
    <% end %>
    seconds
  </div>
  <% end %>
<% end %>

<p>
  <b>Name:</b>
  <%= @challenge.name %>
</p>

<p>
  <b>Description:</b>
  <%= @challenge.description %>
</p>

<p>
  <b>Estimate:</b>
  <%= @challenge.estimate %>
</p>

<p>
  <b>Started at:</b>
  <%= @challenge.started_at %>
</p>

<p>
  <b>Stopped at:</b>
  <%= @challenge.stopped_at %>
</p>

<p>
  <b>Completedin:</b>
  <%= @challenge.completedin %>
</p>

<p>
  <b>User:</b>
  <%= @challenge.user_id %>
</p>

<p>
  <b>Aborted at:</b>
  <%= @challenge.aborted_at %>
</p>


<%= link_to 'Edit', edit_challenge_path(@challenge) %> |
<%= link_to 'Back', challenges_path %>